// Copyright 2025 Robert Adams
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;

using KeeKee.Config;
using KeeKee.Contexts;
using KeeKee.Framework.Logging;

using OMV = OpenMetaverse;

namespace KeeKee.World.LL {
    /// <summary>
    /// A class that creates and instance of a DI registered class.
    /// To use, add InstanceFactory to the class creation invocation
    /// and then do a "_factory.Create<TheClassYouWant>()".
    /// </summary>
    public interface ILLInstanceFactory {
        T Create<T>(params object[] parameters) where T : class;
        LLEntity CreateLLEntity(OMV.Primitive? pPrim, IRegionContext pRContext, IAssetContext pAContext, EntityClassifications pClassification);
        LLEntity CreateLLAvatar(OMV.GridClient pClient, IRegionContext pRContext, IAssetContext pAContext);
        LLEntity CreateLLPhysical(OMV.GridClient pClient, OMV.Primitive? pPrim, IRegionContext pRContext, IAssetContext pAContext);
        public LLRegionContext CreateLLRegionContext(OMV.GridClient pGridClient, OMV.Simulator pSim, IAssetContext pAContext);
    }
    public class LLInstanceFactory : ILLInstanceFactory {

        private readonly IServiceProvider _provider;
        public LLInstanceFactory(IServiceProvider pProvider) {
            _provider = pProvider;
        }

        public T Create<T>(params object[] parameters) where T : class {
            return ActivatorUtilities.CreateInstance<T>(_provider, parameters);
        }

        public LLEntity CreateLLEntity(OMV.Primitive? pPrim, IRegionContext pRContext, IAssetContext pAContext, EntityClassifications pClassification) {
            return new LLEntity(
                _provider.GetRequiredService<KLogger<LLEntity>>(),
                _provider.GetRequiredService<IWorld>(),
                pRContext, pAContext, pPrim, pClassification);
        }

        public LLEntity CreateLLAvatar(OMV.GridClient pClient, IRegionContext pRContext, IAssetContext pAContext) {
            IOptions<LLAgentConfig> pConfig = _provider.GetRequiredService<IOptions<LLAgentConfig>>();
            LLEntity ava = CreateLLEntity(null, pRContext, pAContext, EntityClassifications.AvatarEntity);
            ava.AddComponent<LLCmptAvatar>(new LLCmptAvatar(ava.EntityLogger, ava, pClient));
            ava.AddComponent<LLCmptLocation>(new LLCmptLocation(ava.EntityLogger, ava, pClient));
            ava.AddComponent<LLCmptAgentMovement>(new LLCmptAgentMovement(ava.EntityLogger, ava, pClient, pConfig));
            // stuff generated by CoPilot. Maybe useful later.
            // ava.AddComponent<LLCmptAvatarAppearance>(new LLCmptAvatarAppearance());
            // ava.AddComponent<LLCmptAvatarInventory>(new LLCmptAvatarInventory());
            // ava.AddComponent<LLCmptAvatarActions>(new LLCmptAvatarActions());
            // ava.AddComponent<LLCmptAvatarCommunication>(new LLCmptAvatarCommunication());
            // ava.AddComponent<LLCmptAvatarGestures>(new LLCmptAvatarGestures());
            // ava.AddComponent<LLCmptAvatarGroups>(new LLCmptAvatarGroups());
            // ava.AddComponent<LLCmptAvatarProperties>(new LLCmptAvatarProperties());
            return ava;
        }

        public LLEntity CreateLLPhysical(OMV.GridClient pClient, OMV.Primitive? pPrim, IRegionContext pRContext, IAssetContext pAContext) {
            LLEntity phy = CreateLLEntity(pPrim, pRContext, pAContext, EntityClassifications.PrimitiveEntity);
            phy.AddComponent<LLCmptLocation>(new LLCmptLocation(phy.EntityLogger, phy, pClient));
            return phy;
        }

        public LLRegionContext CreateLLRegionContext(OMV.GridClient pGridClient, OMV.Simulator pSim, IAssetContext pAContext) {
            return new LLRegionContext(
                _provider.GetRequiredService<KLogger<LLRegionContext>>(),
                this,
                _provider.GetRequiredService<IWorld>(),
                pAContext,
                _provider.GetRequiredService<IEntityCollection>(),
                _provider.GetRequiredService<RegionState>(),
                _provider.GetRequiredService<LLTerrainInfo>(),
                pGridClient,
                pSim);
        }

        public override string ToString() {
            return $"LLInstanceFactory";
        }
    }
}

